App\Model\Company:
  type: entity
  repositoryClass: App\Repository\CompanyRepository
  table: companies
  indexes:
    name_index:
      columns: [ name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50
