App\Model\Position:
  type: entity
  repositoryClass: App\Repository\PositionRepository
  table: positions
  indexes:
    name_index:
      columns: [ name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50
